version: 0.2
phases:
  install:
    commands:
      - echo "install phase started at $(date)"
      - echo "Installing API Dependencies..."
      - echo "Installing Ruby dependencies..."
      - rm -rf vendor/cache
      - bundle config set force_ruby_platform true
      - bundle install
      - echo "Client Dependencies..."
      - echo "Node version..."
      - node -v
      - echo "Yarn version..."
      - yarn -v
      - echo "Installing JS dependencies..."
      - yarn install
  pre_build:
    commands:
      - echo "pre_build phase started at `date`"
      - |
        if [ -n "$GIT_REF" ]; then
          GIT_SHA=$(git rev-parse --short "$GIT_REF")
        else
          GIT_SHA=$(git rev-parse --short "$CODEBUILD_RESOLVED_SOURCE_VERSION")
        fi
      - export GIT_SHA
      - git checkout "$GIT_SHA"
      # - echo Running migrations...
      # - bundle exec rake db:migrate
  build:
    commands:
      - echo "build phase started at $(date)"
      # - echo Running tests...
      # - bundle exec rspec spec
      - echo "Building the app..."
      - bundle config set cache_all true
      - bundle package
  post_build:
    commands:
      - echo "post_build phased started at $(date)"
      - |
        if [ "$TRIGGER_REASON" == "PR_merged" ]; then
          echo "Uploading artifacts because TRIGGER_REASON is ${TRIGGER_REASON}"
          zip nd-pharm-starfield-${GIT_SHA}.zip -r * .[^.]* -x "./.git/*" "./.log/*" "./node_modules/*" "./storage/*" "./tmp/*"
          aws s3 cp --sse aws:kms nd-pharm-starfield-${GIT_SHA}.zip s3://codepipeline-us-east-2-273418831284/artifacts/develop/nd-pharm-starfield-${GIT_SHA}.zip
        else
          echo "Skipping bundling and uploading because TRIGGER_REASON is ${TRIGGER_REASON}"
        fi
      - echo "Build completed at `date`"
artifacts:
  files:
    - "**/*"
  exclude-paths:
    - ./nd-pharm-starfield-${GIT_SHA}.zip
