APPLICATION_HOST: localhost:3000
APPLICATION_PROTOCOL: http

GETSTREAM_API_KEY: waz77c4s4g55
GETSTREAM_API_SECRET: 254agpj9xv88f78498cg4twap72w2uj2qf28dqb7ypr4hvdf5hxg9e9ryfmgkesk

# SMTp Info
DEFAULT_FROM: info@starfield.health
SMTP_USERNAME: AKIAWLG36GQC5NKDKJ7P
SMTP_PASSWORD: BDlJdpa/TgFgKbOGK0qrA+1+AXP7HkUgVl9pMQFVxfo2
SMTP_ADDRESS: email-smtp.us-east-1.amazonaws.com
TEST_DEVICE_IDENTIFIER: "9999996"
IGLUCOSE_DEVICE_API_KEY: 2EAF7655-7ABC-4A18-B8FC-B944DF5619A9-1617316449
IGLUCOSE_DEVICE_URL: https://api.iglucose.com/
TEST_PATIENT_IDENTIFIER: "AAD-62201-0"

# these are glucose reading source for Orion
ACCESS_TOKEN_ENDPOINT: https://orionhealth-ndi-preprod.apigee.net/oauth2/token
ACCESS_TOKEN_USERNAME: codelation.apistage
ACCESS_TOKEN_PASSWORD: "@_X78rr8PhB!Z-ez"
ACCESS_TOKEN_AUTH_USERNAME: DGGkA46ciXOBqvVHL30NnH4hR71bFJxC
ACCESS_TOKEN_AUTH_PASSWORD: hPFmVGpAfX3k3cuq
PATIENT_DATA_ENDPOINT: https://hie.stage.ndhin.com/fhir/1.0/

ROLLBAR_ACCESS_TOKEN: 5f39aacafe78444883deb9bb74aa2687
ROLLBAR_ENDPOINT: https://api.rollbar.com/api/1/item/
APP_TIMEZONE: "Central Time (US & Canada)"
AWS_ACCESS_KEY_ID: AKIAWLG36GQC5CBMGOHZ
AWS_BUCKET: starfield-staging
AWS_REGION: us-east-2
AWS_SECRET_ACCESS_KEY: AVAbu+QNaD/yQtbeOlMZmaMJDnI80EAqUOLPBYq6

AWS_SQS_ACCESS_KEY: AKIAWLG36GQC6MUXP4MB
AWS_SQS_SECRET_KEY: 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
AWS_SQS_REGION: us-east-2
AWS_SQS_QUEUE_NAME: starfield-dev
AWS_SQS_QUEUE_URL: https://sqs.us-east-2.amazonaws.com/436400436229/starfield-dev

# this urls is to fetch medications
RX_NORM_URL: https://rxnav.nlm.nih.gov/REST/drugs

# this is for 2FA 
# TEXT_MAGIC_USERNAME: suman.koirala@codelation.com
# TEXT_MAGIC_API_KEY: wyMVsEqQxydwi3JOFMCCEr3G3xMkaH 
TEXT_MAGIC_USERNAME: jessejohnson
TEXT_MAGIC_API_KEY: L7Y4OFQVRicfROVr1tcvD8fo4zJgtQ
DEVISE_TWO_FACTOR_KEY: jfioeji0qu432q80ujr0jfds
TWO_FACTOR_INTEGRATED: "false"

# Dexcom keys
# DEXCOM_CLIENT_ID: lnGzu7dUarKdsfvfoCIJ5NRPynF1QznO
# DEXCOM_CLIENT_SECRET: NEQkmAwJ2RLa3eLE
# DEXCOM_OAUTH_URL: https://sandbox-api.dexcom.com/v2/oauth2/login
# DEXCOM_TOKEN_URL: https://sandbox-api.dexcom.com/v2/oauth2/token
# DEXCOM_EGV_URL: https://sandbox-api.dexcom.com/v2/users/self/egvs
# DEXCOM_REDIRECT_URL: http://localhost:3000/receive_authorization_from_dexcom

# ADT Keys
ADT_SFTP_USERNAME: "ndi-star-int-skoirala"
ADT_SFTP_PASSWORD: "<i[+JLC$xf!Wp]y(6>F+"
ADT_SFTP_HOST: "ndi.sftp.orionhealthcloud.com"
ADT_SFTP_OUTBOUND_DIR: "STARtoNDHIN"
ADT_SFTP_INBOUND_DIR: "NDHINtoSTAR/ADT"
ADT_NOTIF_DELAY_MIN: "10"
ADT_INTEGRATON_ON: "false"

# T: Test, P: Production
BILLING_INTEGRATON_ON: "true"
INTERCHANGE_USE_INDICATOR: "T" 
EDINATION_API_KEY: "3ecf6b1c5cf34bd797a5f4c57951a1cf"
ENINATION_API_X12_URL: "https://api.edination.com/v2/x12/write?preserveWhitespace=false&charSet=utf-8" 
# ask these info
BILLING_RECEIVING_ORG: "Billing Receiving Org"
BILLING_RECEIVER_IDENTIFIER_CODE: "123123"
MEDICARE_OR_MEDICAID_PROVIDER_NUMBER: "12341234"
BUSINESS_APPLICATION_NUMBER: "123123A"
BILLING_INTERCHANGE_RECEIVER_ID: "123A"
BILLING_INTERCHANGE_SENDER_ID: "123B"

FEATURE_BULK_UPLOAD_ON: "true"
FEATURE_REPORTS_ON: "true"

# NDIIS Keys
NDIIS_API_SUBSCRIPTION_KEY: "9fe9014758f74d45be87b1ba2ec3d349"
NDIIS_API_END_POINT: "https://api-test.ndiis.org"
NDIIS_TOKEN_END_POINT: "https://login.microsoftonline.com/ndiistestb2c.onmicrosoft.com/oauth2/v2.0/token"
NDIIS_CLIENT_ID: "0ef72c82-cd8a-4832-8be4-a3eb7270418f"
NDIIS_CLIENT_SECRET: "4XY8Q~t8J4MeQ-UWQmYkG1LOeLyGK.lZkBJvUbi7"
NDIIS_OAUTH_SCOPE: "https://ndiistestb2c.onmicrosoft.com/0ef72c82-cd8a-4832-8be4-a3eb7270418f/.default"


# ChangeHealthcare APIs
CHANGE_HEALTHCARE_CLIENT_ID: "n8hwUosyk6cKtJ5yfKQcREBoCStSGcQh"
CHANGE_HEALTHCARE_CLIENT_SECRET: "nA5tWytPaa2ULZ8m"
CHANGE_HEATHCARE_API_URL: "https://sandbox.apigw.changehealthcare.com"