const globals = {
  states: [
    "AL",
    "AK",
    "AS",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FM",
    "FL",
    "GA",
    "GU",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MH",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "MP",
    "OH",
    "OK",
    "OR",
    "PW",
    "PA",
    "PR",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VI",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
  ],
  countries: [
    'United States', 
  ],  
  devices: ["Dexcom CGM"],
  genders: ["Male", "Female"],
  individual_action_menu_options: [
    ["Complete this action", "complete"],
    ["Mark this action incomplete", "incomplete"],
    ["Unassign this action from provider", "unassign"],
    ["Assign this action to a provider", "assign"],
    ["Dismiss this action", "dismiss"],
    ["Defer this action", "defer"],
  ],
  complete_action_menu_options: ["Mark this action incomplete"],
  group_action_menu_options: [
    "Complete All Actions",
    "Unassign Actions From Provider",
  ],
  complete_group_action_menu_options: ["Mark All Actions Incomplete"],
  assignment_type_list_options: [
    "My Actions",
    "Assigned Actions",
    "Unassigned Actions",
    "All Actions",
  ],
};

export const raceOptions = ["Hispanic or Latino", "Not Hispanic or Latino"];
export const ethnicityOptions = [
  "White",
  "Black or African American",
  "American Indian or Alaskan Native",
  "Asian",
  "Native Hawaiian or Other Pacific Islander",
];

export default globals;
